install_prefix = "/g/g90/lumsden1/ws/insitu_benchmark/Src_Benchmark_InSitu/_catalyst_install"
out_dir = "/g/g90/lumsden1/ws/insitu_benchmark/Src_Benchmark_InSitu/submit/basic_seq/lib_path_test_out"
natoms = 40

[extra_envs]
LD_LIBRARY_PATH = "/g/g90/lumsden1/ws/rdma-core/build/lib:$LD_LIBRARY_PATH"
UCX_TLS="ud_verbs,rc_verbs"
UCX_LOG_LEVEL="data"

[dtl]
consumer_path = "/tmp/lumsden1/dyad_basic_sequential"
producer_path = "/tmp/lumsden1/dyad_basic_sequential"
kvs_namespace = "dyad_basic_sequential"
dtl_mode = "UCX"
