[build]
dtl = "dyad"
build_type = "Release"
CC = "/usr/tce/packages/gcc/gcc-12.1.1-magic/bin/gcc"
CXX = "/usr/tce/packages/gcc/gcc-12.1.1-magic/bin/g++"
FC = "/usr/tce/packages/gcc/gcc-12.1.1-magic/bin/gfortran"
prefix = "./_tioga_install"

[build.extra_cmake_config]
MPI_C_COMPILER = "/opt/cray/pe/mpich/8.1.25/ofi/crayclang/10.0/bin/mpicc"
MPI_CXX_COMPILER = "/opt/cray/pe/mpich/8.1.25/ofi/crayclang/10.0/bin/mpicxx"
MPI_Fortran_COMPILER = "/opt/cray/pe/mpich/8.1.25/ofi/crayclang/10.0/bin/mpif90"

[dtl.dspaces]
class_prefix = "DSpaces"
file_prefix = "dspaces"
cmake_target = "dspaces_dtl"
needs_mpi = true

[dtl.dyad]
class_prefix = "Dyad"
file_prefix = "dyad"
cmake_target = "dyad_dtl"
needs_mpi = false

[[dtl.dyad.cmake_options]]
"name" = "DYAD_GIT_TAG"
"default_value" = "main"
"description" = "The Git tag, branch name, etc. to use when checking out DYAD"

[[dtl.dyad.cmake_options]]
name = "DYAD_API"
default_value = "wrapper"
description = "The type of DYAD API to use when building. Can be either 'wrapper' or 'stream'"
