FROM fluxrm/flux-sched:focal

ARG JUPYTERHUB_VERSION=2.3.1

RUN sudo apt-get update
RUN DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install \
    python3-pip \
    npm \
    curl \
    libboost-dev \
    libboost-filesystem-dev \
    libboost-iostreams-dev \
    libboost-serialization-dev \
    python3-numpy \
    gfortran \
    openmpi-bin \
    openmpi-common \
    && sudo apt-get clean \
    && sudo apt-get autoremove \
    && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install --upgrade pip \
    && pip3 install setuptools-rust zipp==3.7.0 \
    && pip3 install jupyterhub==${JUPYTERHUB_VERSION} \
    && sudo npm install -g configurable-http-proxy \
    && python3 -m pip install jupyterlab notebook \
    && echo "export PATH=$HOME/.local/bin:$PATH" >> "$HOME/.bashrc"

RUN git clone https://github.com/openucx/ucx.git \
    && cd ucx \
    && git checkout v1.13.1 \
    && ./autogen.sh \
    && ./configure --disable-optimizations --enable-logging --enable-debug --disable-assertions --enable-mt --disable-params-check \
       --without-go --without-java --disable-cma --without-cuda --without-gdrcopy --without-verbs --without-knem --without-rmdacm \
       --without-rocm --without-xpmem --without-fuse3 --without-ugni --prefix=/usr CC=$(which gcc) CXX=$(which g++) \
    && make -j \
    && sudo make install \
    && cd .. \
    && rm -rf ucx

RUN git clone https://github.com/TauferLab/dyad.git \
    && cd dyad \
    && git checkout dev-day-2023 \
    && cp -r use_cases/shuffle ../dl_shuffle \
    # Comments out the build cmds for DYAD because the insitu benchmark will build DYAD instead
    # && ./autogen.sh \
    # && ./configure --prefix=/usr CC=$(which gcc) CXX=$(which g++) \
    # && make -j \
    # && sudo make install \
    && cd .. \
    && rm -rf dyad

COPY --chown=fluxuser:fluxuser dev_day_demo.cmake .

ADD Src_Benchmark_InSitu ./Src_Benchmark_InSitu

RUN cd Src_Benchmark_InSitu \
    && sudo mkdir build \
    && cd build \
    && sudo cmake -C ../../dev_day_demo.cmake .. \
    && sudo make -j \
    && sudo make install \
    && cd ../../ \
    && sudo rm -rf Src_Benchmark_InSitu

RUN cd dl_shuffle \
    # && CC=$(which gcc) CXX=$(which g++) make all \
    && cd ..

COPY --chown=fluxuser:fluxuser ecp23-flux-dyad.ipynb .
COPY --chown=fluxuser:fluxuser dyad_example1.svg .
COPY --chown=fluxuser:fluxuser dyad_example2.svg .
COPY --chown=fluxuser:fluxuser Flux-logo.svg .

ENV SHELL=/usr/bin/bash
ENV FLUX_URI_RESOLVE_LOCAL=t

CMD PATH=$HOME/.local/bin:$PATH \
    flux start --test-size=4 /home/fluxuser/.local/bin/jupyterhub-singleuser
